//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesktopssEntities1 : DbContext
    {
        public DesktopssEntities1()
            : base("name=DesktopssEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor_Log> Doctor_Log { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<patients_log> patients_log { get; set; }
    }
}
