//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Doc_id { get; set; }
        public Nullable<int> Room_Number { get; set; }
        public Nullable<int> Nurse_id { get; set; }
        public Nullable<int> med_code { get; set; }
    }
}
